server:
  port: 0

spring:
  application:
    name: rental-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh

api:
  topic:
    book:
      status-event: BOOK-STATUS-EVENT
      stock-event: BOOK-STOCK-EVENT
      delivery-event: DELIVERY-EVENT

