server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/devHTak/MsaLibrary/config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh